Added slaves field in Executor v2 CRD
kubeshop/testkube-operator pull request #176
Opened 2023-09-19 11:41 UTC by hiteshwani

## Pull request description 
Created v2 version for adding slaves filed in Executor CRD.
```
 slaves:
   description: Slaves data to run test in distributed environment
   properties:
     image:
       type: string
   required:
   - image
   type: object
````

## Checklist (choose whats happened)

- [ ] breaking change! (describe)
- [x] tested locally
- [x] tested on cluster
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

## Breaking changes

-

## Changes

-

## Fixes

-

2023-09-19 11:47 UTC, vsukhin commented
Why are we creating executorV2? Because of slave property?

2023-09-19 11:53 UTC, hiteshwani commented
Yes, @vsukhin. 
We've discussed this with @dejanzele as well, and we've decided to create a new version, v2, to incorporate the 'slaves' field into the Executor CRD.

2023-09-19 11:57 UTC, vsukhin commented
We intriduce new version when we break compaitibility between versions. We don't use minoj versions, but this is definitely minor one

2023-09-20 09:20 UTC, dejanzele commented on Dockerfile
> +FROM  alpine:3.18.0
Can you revert this change so it doesn't break our CI?

2023-09-20 09:22 UTC, dejanzele commented on controllers/executor/executor_controller.go
> +		For(&executorv2.Executor{}).
I think we can revert to V1

2023-09-20 09:22 UTC, vsukhin requested changes
we increase major version only for incompatible changes

2023-09-21 07:37 UTC, hiteshwani commented
Closing this PR. I will create new PR to add slave configuration in Executor V1 CRD.

2023-09-21 07:37 UTC, closed without merging